project:
  type: book

book:
  title: "Finanzanalyse Scout24"
  author: ["Rafael Gabriel Angel", "Teammitglied"]
  chapters:
    - index.qmd
    - 04_report/01_einleitung.qmd
    - 04_report/02_unternehmen.qmd
    - 04_report/03_branche_peers.qmd
    - 04_report/04_finanzanalyse.qmd
    - 04_report/05_bewertung.qmd
    - 04_report/06_fazit.qmd

format:
  pdf:
    toc: true
    number-sections: true
    lof: true
    lot: true
