lang: de
date: today
date-format: "D. MMMM YYYY"

project:
  type: book

book:
  title: ""
  author: []
  chapters:
    - index.qmd
    - 04_report/01_einleitung.qmd
    - 04_report/02_unternehmen.qmd
    - 04_report/03_branche_peers.qmd
    - 04_report/04_finanzanalyse.qmd
    - 04_report/05_bewertung.qmd
    - 04_report/06_fazit.qmd

format:
  pdf:
    title-block-style: none
    title: ""
    author: ""
    date: ""
    toc: true
    toc-depth: 6
    number-sections: true
    lof: true
    lot: true

    fontsize: 12pt
    linestretch: 1.5
    geometry:
      - left=4cm
      - right=2cm
      - top=4cm
      - bottom=2cm

    cite-method: citeproc

    include-before-body:
      - 04_report/titlepage.tex
    include-in-header:
      - 04_report/header.tex

execute:
  echo: false
  warning: false
  message: false

editor: visual
